### ISSUE TITLE
Ability to disable splitting by CR and LF when using execute.

### ISSUE THREAD

**Issue by Steve0Greatness** [czproject/git-php#100]
In Git, there's a `cat-file` command, which allows you to get a file at a particular point in time. These files aren't always in plain text, so it's important to keep each byte the same to prevent corruption. Unfortunately, since `\r\n` and `\r` are both replaced with just `\n` this does not preserve the bytes, and makes it impossible to recover back to the file's original state. I ask that you add a named argument to `GitRepository->execute` which would allow skipping the step that splits by newlines and carriage returns.

**Comment by janpecha** [comment]
Hi, please try `dev-master` version. I added ability to get raw output via `$repository->run()` method:

```php
$repository->run('cat-file')->getOutputAsString();
```

**Comment by Steve0Greatness** [comment]
That works perfectly! Thank you.

**Comment by janpecha** [comment]
You're welcome. I just released new version 4.3.0 :)
