### ISSUE TITLE
git commit, addRemote and push failed

### ISSUE THREAD

**Issue by thamaraikrishnan** [czproject/git-php#11]
Hi, 
I am new to git process. I have tried to use all functions which are all working fine except commit, addRemote and push commands. I guess, the problem is due to user credentials. Please guide me to set user credentials using this git-php lib. Please help me to move forward for fixing these issues if it is not related to user credentials.

Errors:
git commit Error : "Command 'git commit -m \"init commit\"' failed."
git add remote Error : "Command 'git remote add \"origin\" \"https://user:password@github.com/user/demo.git\"' failed."

Thanks in advance...

**Comment by janpecha** [comment]
Hi, thanks for report, this is strange.

Try execute commands manually in command line and check if they works.

If they works, dump current working directory and exit-codes. Insert `var_dump` before this line https://github.com/czproject/git-php/blob/master/src/GitRepository.php#L584:

```
var_dump(array($ret, getcwd(), $this->cwd, $this->repository));
```

And sent me the output here.

**Comment by janpecha** [comment]
One additional question - what is your OS?

**Comment by thamaraikrishnan** [comment]
Hi Janpecha,

Output: 
--------
cmd : git commit -m "init commit"

var_dump:
-----------
<pre>
    <pre class='xdebug-var-dump' dir='ltr'>
        <small>F:\latte\api_v2\core\vendor\czproject\git-php\src\GitRepository.php:586:</small>
        <b>array</b>
        <i>(size=4)</i>
  0
        <font color='#888a85'>=&gt;</font>
        <small>int</small>
        <font color='#4e9a06'>128</font>
  1
        <font color='#888a85'>=&gt;</font>
        <small>string</small>
        <font color='#cc0000'>'F:\latte\devlibs\tmp\brewdemo'</font>
        <i>(length=29)</i>
  2
        <font color='#888a85'>=&gt;</font>
        <small>string</small>
        <font color='#cc0000'>'F:\latte\api_v2\core'</font>
        <i>(length=20)</i>
  3
        <font color='#888a85'>=&gt;</font>
        <small>string</small>
        <font color='#cc0000'>'F:\latte\devlibs\tmp\brewdemo'</font>
        <i>(length=29)</i>
    </pre>

print_r:
--------
Array
(
    [0] => 128
    [1] => F:\latte\devlibs\tmp\brewdemo
    [2] => F:\latte\api_v2\core
    [3] => F:\latte\devlibs\tmp\brewdemo
)

OS is Windows 10. 

But, I have tried this in the linux box (Cent OS 6.7) where nothing is working for me. So, i don't know what went wrong. Then i moved to windows to verify this. I faced those issues (commit, add remote and push).

Thanks...

**Comment by thamaraikrishnan** [comment]
In linux box:
cmd : git commit -m 'init commit'

output:
array(4) {
  [0]=>
  int(127)
  [1]=>
  string(17) "/repo_manage/demo"
  [2]=>
  string(36) "/stagebrewservices/latte_v2/api/core"
  [3]=>
  string(17) "/repo_manage/demo"
}

Note: We have not installed the git server on both Windows and Linux server.

**Comment by janpecha** [comment]
Yeah, you need install `git` client (on Ubuntu/Debian via `apt-get install git`) and it must be in `PATH`. This PHP library is only wrapper on command line.

For Linux box exit-code 127 means "command not found".

**Comment by thamaraikrishnan** [comment]
Yes.. I installed git client. Now it is working till commit process.

Push origin command is not working. Thanks a lot for your support.

But, I can execute the command by manually which asks to enter credentials also.

output:
--------
git push origin 

array(4) {
  [0]=>
  int(128)
  [1]=>
  string(22) "/repo_manage/sampleone"
  [2]=>
  string(36) "/stagebrewservices/latte_v2/api/core"
  [3]=>
  string(22) "/repo_manage/sampleone"
}

**Comment by janpecha** [comment]
`git push` is a little bit problematic. Currently is not posiblle take user+password into `$git->push()` method. I will try find any solution for it, but it takes some time. You can temporarily:

1) use SSH (+SSH key) instead of HTTPS with user+password
2) save credentials to cache (see http://www.tilcode.com/push-github-without-entering-username-password-windows-git-bash/ or https://help.github.com/articles/caching-your-github-password-in-git/)
3) insert password & user into `remote` (git add remote origin "https://user:password@server/path")

**Comment by thamaraikrishnan** [comment]
Ok.. Thanks for your support...
