### ISSUE TITLE
git push sends output to stderr

### ISSUE THREAD

**Issue by Park0** [czproject/git-php#12]
It seems that git push sends part of the output to stderr. 

I think it would be best to add --porcelain to a push command on default.

https://git-scm.com/docs/git-push#git-push---porcelain

**Comment by janpecha** [comment]
Hi, thanks for report. I added redirect of STDERR to STDOUT (43c646c6c444d5196ff2dd387c60556193b82c7a). Try if it helps.

**Comment by Park0** [comment]
This fixed it for me. Thanks for the very fast response.
