### ISSUE TITLE
Setting and pushing to new remote

### ISSUE THREAD

**Issue by joum** [czproject/git-php#13]
Hello!

I've been trying to use your library to push to a new repository created via GitHub API on my app.

I've been able to make everything work so far, but I am having trouble with the `git remote add` and `git push` bits of my flow.

Imagine I wanted to do exactly as GitHub suggests when setting a new remote and pushing to it:

`git remote add origin git@github.com:organization/repository.git`

and then

`git push -u origin master`

How would I achieve this?

Here's what I've been trying:

```
  $new_repository->addRemote('origin', 'git@github.com:organization/repository.git');

  $new_repository->push('origin', ['--set-upstream']);
```

But this keeps failing with this being logged:

> Cz\Git\GitException: Command 'git push origin '--set-upstream'' failed (exit-code 128). in Cz\Git\GitRepository->run() (line 584 of /vagrant/www/vendor/czproject/git-php/src/GitRepository.php).

Can you provide any insight?

**Comment by joum** [comment]
Nevermind. I just added `master` to the parameters in the push method and it worked. 

Cheers, good job!

**Comment by janpecha** [comment]
Hi, thanks for report and solution.
