### ISSUE TITLE
Version 4.0

### ISSUE THREAD

**Issue by janpecha** [czproject/git-php#18]
```php
$git = new CzProject\GitPhp\Git;
$repo = $git->init(__DIR__ . '/directory');
$repo->commit('message');

$repo2 = $git->open(__DIR__ . '/repo2'); // or new GitRepository(__DIR__ . '/repo2')
$repo->run('remote set-branches', 'origin', 'branch-1');
```
----

* <del>remove `IGit` interface</del>
* <del>add new factory class `Git` with methods:</del>
  * <del>`open($directory): GitRepository`</del>
  * <del>`init($directory, $params): GitRepository` (replacement for `GitRepository::init()`)</del>
  * <del>`clone($url, $directory): GitRepository` (replacement for `GitRepository::cloneRepository()`)</del>
  * <del>`isRemoteUrlReadable($url, $refs): bool` (replacement for `GitRepository::isRemoteUrlReadable()`)</del>

**GitRepository**

* <del>make `run()` public</del>
* <del>remove `begin()` & `end()`</del>
* <del>remove static methods `init`, `cloneRepository`, `isRemoteUrlReadable`</del>
* <del>move static methods `extractRepositoryNameFromUrl` & `isAbsolute` to new class `Helpers`</del>

**Internals**

* <del>maybe use https://github.com/czproject/runner</del>
* <del>introduce new interface IGitRunner</del>
  * <del>new class `CliRunner` (default)</del>
  * <del>new class `MemoryRunner` (for tests)</del>
* <del>change `@return self` to `@return static` in PhpDocs</del>
* <del>use `proc_open` instead of `exec`</del> (#33)
* <del>updated tests</del>
* <del>use `$var` name in PhpDocs</del>
* <del>use PHPStan</del>
* <del>support for PHP 8.x</del>
* <del>GitHub Actions</del>

**Comment by ribeiropaulor** [comment]
Is there any reason not to use Phpunit for testing?

**Comment by janpecha** [comment]
Problem with testing is elsewhere. Currently we execute CLI commands directly in tests. But it makes testing special cases and broken states very hard.

**Comment by r7vmc** [comment]
some gits need a password to get cloned is there an option to put password here?

**Comment by janpecha** [comment]
Hello, options are still same:

1) use SSH instead of HTTPS
2) store credentials to Git Credential Storage
3) insert user and password into remote URL
4) for `push()` is there `--repo` argument

Details are in troubleshooting in readme under ["Remotes" section](https://github.com/czproject/git-php#remotes).

**Comment by r7vmc** [comment]
@janpecha nevermind I got it working
but I've noticed that phpstorm keeps telling me "Unhandled \Cz\Git\GitException" when using Clone

**Comment by janpecha** [comment]
@r7vmc If you can, try collect some details and open new issue if needed. I don't know when PhpStorm reports "unhandled exceptions" but `clone` may fail and throws `Cz\Git\GitException`. For that case try add `try catch` block into your code.

**Comment by r7vmc** [comment]
@janpecha well nevermind my project works perfectly even with than error
