### ISSUE TITLE
Git commit fails some times

### ISSUE THREAD

**Issue by sarathbabuSwamynathan** [czproject/git-php#19]
Hi, we used to commit from our local system to git repository. overall its working fine.
but, some time I am getting following error,

Cz\Git\GitException: Command 'git commit '1779e4620f28568d37bc6d218359d99f/ed6879fe3ab14763885e8f1c41b2e22b' -m 'Commit : 489b024e153b433394fd83add47be80d_enterprise_1.0.0'' **failed** (exit-code 128). in [my application path]

it is working fine when i commit following command manually (through putty),
git commit '1779e4620f28568d37bc6d218359d99f/ed6879fe3ab14763885e8f1c41b2e22b' -m 'Commit : 489b024e153b433394fd83add47be80d_enterprise_1.0.0''

* but through application it is not working when i am having new file in that folder.

When I check status in that directory it will be like in attachement
![git_error](https://user-images.githubusercontent.com/19778435/36204284-b1be8072-11b0-11e8-8114-5414474eb6e7.png)

I don't know what is the problem.
Thanks in advance!!

**Comment by janpecha** [comment]
Hi, thanks for report. It's really weird. Can you give more informations? For example your code snippet, OS, Git version,... 

But I don't idea what causes it. May be:

* is wrong "current working directory" (`git commit` runs in wrong directory) - try check `getcwd()`
* or try modify method `GitRepository::commit`. Change this part:

```php
return $this->begin()
	->run("git commit", $params, array(
		'-m' => $message,
	))
	->end();
```

to

```php
return $this->begin()
	->run("git update-index -q --refresh")
	->run("git commit", $params, array(
		'-m' => $message,
	))
	->end();
```

and test it. If it will help, I will release new version with this change.

**Comment by janpecha** [comment]
Alternatively, try call `$repo->addFile()` before calling `commit()`.

**Comment by sarathbabuSwamynathan** [comment]
I will try with this and let you know.
Thank you.

**Comment by sarathbabuSwamynathan** [comment]
I tried with above methods, it don't work.
* In Apache server it was working fine, last week we moved to nginx
* Is there any configuration need to add for nginx server for git commit process
* we are using nginx : 1.12.2 and centos verion : 7.4.1708

**Comment by janpecha** [comment]
I don't know, I never run Git under Apache/nginx server. It seems to me like problem with permissions - file has another user/group than Git process or there is wrong `umask` setting in nginx (https://stackoverflow.com/questions/11584021/nginx-php-fpm-umask-setting).

**Comment by sarathbabuSwamynathan** [comment]
After i delete my git repository and I have created new one and cloned it, this issue gone.
Now everything is fine.

But, I still I have no idea how this issue is occurs. (I have created my new repository with the same settings as previous one.)

**Comment by janpecha** [comment]
It's really weird. Maybe some files in `.git` folder had wrong permissions. Who know...

So I close this issue for now because it seems not related to this library. Feel free to reopen if needed.

**Comment by sarathbabuSwamynathan** [comment]
yea sure. Thanks.
