### ISSUE TITLE
Feature request: add worktree functions support

### ISSUE THREAD

**Issue by ofir-petrushka** [czproject/git-php#22]
Feature request: add worktree functions support

MVP is just the `add` function to create a new linked repository directory

https://git-scm.com/docs/git-worktree

**Comment by janpecha** [comment]
Hi, I just added new method `execute` to `GitRepository`. Now you can use for example:

```php
$repo->execute(array('worktree', 'add', $path));
```

**Comment by ofir-petrushka** [comment]
Sounds good, Thank you. 
Will take a few days before I can try it out, but sounds great to have the flexibility like that.
