### ISSUE TITLE
Class 'GitRepository' not found

### ISSUE THREAD

**Issue by abdulazizalrawahi** [czproject/git-php#27]
I am working on laravel framework. I installed this through composer.
$repo = GitRepository::init('/path/to/repo-directory', array(
	'--bare', // creates bare repo
));
In this line I get error
"Class 'GitRepository' not found"

**Comment by janpecha** [comment]
Hello, you must use FQN `Cz\Git\GitRepository` (or `use` statement in file header).

**Comment by abdulazizalrawahi** [comment]
Thanx. This solved my issue
