### ISSUE TITLE
Set Email Pushing?

### ISSUE THREAD

**Issue by herohamp** [czproject/git-php#28]
How can I set the email and name of the person pushing to a git repo?

**Comment by janpecha** [comment]
Hello, what do you exactly mean? Email and name of commit author (`$git->commit()`), or email and name used as credentials for pushing to remote repository (`$git->push()`)?

For `commit()` you can try use `--author` argument (see https://git-scm.com/docs/git-commit):

``` php
$git->commit('message', array('--author' => 'A U Thor <author@example.com>'));
```

For `push()` you can try Troubleshooting tips from this section https://github.com/czproject/git-php#remotes:

1) use SSH
2) store credentials to Git Credential Storage
3) insert user and password into remote URL (for example `git remote add origin https://user:password@server/path/repo.git`)
4) for `push()` you can use `--repo` argument (`$git->push(NULL, array('--repo' => 'https://user:password@server/path/repo.git'));`)

**Comment by herohamp** [comment]
I meant `$git->commit('message', array('--author' => 'A U Thor <author@example.com>'));`

Thank you I was not aware of the --author argument
