### ISSUE TITLE
Git log getter

### ISSUE THREAD

**Issue by Radiergummi** [czproject/git-php#31]
I'm using `git-php` to generate a changelog for our application. To render the git log, I'm currently parsing the output of `$repo->execute('log')`, splitting each line and parsing depending on the first word (commit, author, date, none, etc).  
I think it'd be nice if `git-php` supported something along these lines, maybe providing an array or a `GitLogEntry` object or similar.

**Comment by janpecha** [comment]
Solved #36

**Comment by Radiergummi** [comment]
Hey @janpecha I'm really sorry for not replying to you, as it happens I completely lost track of this. Thank you for implementing it on yourself regardless! 😊
