### ISSUE TITLE
Restore previous working directory after throwing a GitException

### ISSUE THREAD

**Issue by derUli** [czproject/git-php#41]
I noticed that you change the working directory in your class.
After a successfull action you call your end() method to restore the previous working directory.
But if you throw a GitException if something goes wrong, end() isn't called.

So applications which uses this lib have a wrong cwd after a GitException happend.
I had to manually chdir to my applications main dir.

**Comment by janpecha** [comment]
Hello, yes, I know about it, but it can't be easily fixed in version 3.x because it will be big BC break. I plan fix it in version 4.0 (#39).

**Comment by janpecha** [comment]
Fixed by 136879aa1e714125655556a1cbd4d13f04c7ed51
