### ISSUE TITLE
escapeshellarg not working on Windows

### ISSUE THREAD

**Issue by mtveerman** [czproject/git-php#44]
I have an issue with this line:
https://github.com/czproject/git-php/blob/eed45e3201d532c109c6573dff752a9c918dc5b1/src/GitRepository.php#L695

... on Windows. As described here:
https://www.php.net/manual/en/function.escapeshellarg.php#123718

I now solved it by creating a new class extending GitRepository, overwriting the `execute` and ` processcommand` methods, where I rewrite the escape lines. 
```php
if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
                        $cmd[] = $_c . self::escape_win32_argv($value);
                    } else {
                        $cmd[] = $_c . escapeshellarg($value);
                    }
```
where the ` escape_win32_argv()` function is from the above mentioned topic at the PHP site.

**Comment by janpecha** [comment]
Thanks for report, I will look at it.
