### ISSUE TITLE
Cloning particular branch

### ISSUE THREAD

**Issue by talk2cerlin** [czproject/git-php#6]
Looks like there is no option to clone particular branch.

Is there any plan to add that or should i send a pull request?

**Comment by janpecha** [comment]
Hi!

I added new argument `$params` into `cloneRepository()`. You can use

``` php
GitRepository::cloneRepository('git@repo', 'directory', array(
  '--branch' => 'branch-name',
))
```
for cloning of particular branch.

It has one side-effect - if you pass own `$params`,  default parameter `-q` is ignored (https://github.com/czproject/git-php/blob/master/src/GitRepository.php#L615). Thanks to is cloning status printed into STDOUT. It solves maybe issue #5.

Upgrade to new version `3.7.0`.

**Comment by talk2cerlin** [comment]
Thanks for the quick reply and fix. I am impressed. 

One quick thing is the `output` from the `exec` command is saved into `$output` variable and i dont see any option to take it and echo it. the code which i am referring is [here](https://github.com/czproject/git-php/blob/master/src/GitRepository.php#L623)

**Comment by janpecha** [comment]
Without `-q` parameter is output of `git clone` directly printed on screen (tested on Ubuntu).

**Comment by talk2cerlin** [comment]
oh thanks.
