### ISSUE TITLE
Return type annotations erroneously specify self

### ISSUE THREAD

**Issue by JohanFredrikVaren** [czproject/git-php#61]
All methods in the Cz\Git\GitRepository class that return either `$this` or `static` annotate `self` as their return type. This may cause IDEs (e.g. PhpStorm) to warn about type incompatibility between Cz\Git\GitRepository and extensions of that class.

Given the following extension of \Cz\Git\GitRepository:
```
<?php
namespace App\Git;

class GitRepository extends \Cz\Git\GitRepository {

	/**
	 * Indicates whether or not there are any unstaged changes at a file/path.
	 *
	 * @param string $path
	 * @return bool
	 */
	public function hasPathChanges(string $path): bool {
		$this->begin();
		$resultCode = null;
		$output = [];
		exec("git diff --exit-code '$path'", $output, $resultCode);
		$this->end();
		return $resultCode == 1;
	}

}
```

And given the following use of that extension:
```
<?php
namespace App;

use App\Git\GitRepository;

class VersionControl {

	private ?GitRepository $clonedRepo = null;

	public function doNeatStuff(Project $project): bool {
		# Doing some neat stuff here
		GitRepository::cloneRepository($project->getPath(), $this->getClonePath($project))
		# ... and some more neatness
	}

}
```

This will cause PhpStorm to raise the following alert for the method call made in VersionControl::doNeatStuff():

> Incompatible types: Expected property of type '\App\Git\GitRepository|null', '\Cz\Git\GitRepository' provided

This is contrary to the reality of the matter, as \Cz\Git\GitRepository::cloneRepository() does not explicitly instantiate `\Cz\Git\GitRepository` objects, but rather `static` objects.

Similarly, non-static methods claim to return `self` instances, when they should rather claim to return `Cz\Git\IGit` type objects.

**Comment by janpecha** [comment]
Closed via #62
