### ISSUE TITLE
getLastCommitId fails

### ISSUE THREAD

**Issue by clindh** [czproject/git-php#70]
As the CommandProcessor is putting sinqle quotes around the argument that has double quotes (--pretty=fomat:"%H") to "git log", executed by GitRepository::getLastCommitId, the commit ID is then output with surrounding double quotes

This causes CommitId to throw "Invalid commit ID"

CommandProcessor generates this command,
    git log '--pretty=format:"%H"' -n 1
which when executed returns 
   "8d14d508186179480bc35a5c0ab6d9a0f6db863b"

Had it instead been
   git log --pretty=format:"%H" -n 1
or
   git log '--pretty=format:%H' -n 1
it would work: 
   8d14d508186179480bc35a5c0ab6d9a0f6db863b

**Comment by janpecha** [comment]
Thanks for report, fixed in version `4.0.2`.
