### ISSUE TITLE
Can we access the private repositories with username and password. ?

### ISSUE THREAD

**Issue by kvvaradha** [czproject/git-php#72]
Hi 

thank you for trying to bring a great feature into PHP.

Can you tell me is it possible to bring the pirvate repositories clone, git and push with help your library ?

**Comment by kvvaradha** [comment]
thank you. but i am not getting the way to do it, can you provide an example? Which will help me to try this.

**Comment by kvvaradha** [comment]
hi again, thank you i found it, its useful to check it. 
i need one more help from you. 

is it available to get the files changed from the Commit class. As i checked i think there is no such a thing is there for now. ?

**Comment by kvvaradha** [comment]
Provide me a simple example if possible. thank you

**Comment by janpecha** [comment]
Hi, `Commit` class cannot get list of changed files but you can use custom call `$repo->execute()` (https://github.com/czproject/git-php#other-commands)

**Comment by kvvaradha** [comment]
thank you, i will check the command
