### ISSUE TITLE
How to add all files after initializing a new repo?

### ISSUE THREAD

**Issue by talk2cerlin** [czproject/git-php#8]
I wanted to clone a repo and create new repo out of it with some minor modifications

Unfortunately there is no method to add all files in one shot for my initial commit. Is there any way i can do that?

**Comment by janpecha** [comment]
Hi. Maybe will work `$repo->addFile('.');`

**Comment by talk2cerlin** [comment]
My current solution is 


    $repo = GitRepository::init($project_name);

    $files = array_diff(scandir($project_name), array('..', '.'));
                
    $repo->addFile($files)

**Comment by talk2cerlin** [comment]
`$repo->addFile('.');` may fail on deleted files in which it requires `--all` flag

**Comment by talk2cerlin** [comment]
My solution didnt work as its trying to add folders which are ignored in the `.gitignore` file. Now using your solution.

**Comment by janpecha** [comment]
Try current master branch - I added new method `$repo->addAllChanges()` - it's call `git add --all`.

**Comment by talk2cerlin** [comment]
Please close this issue after releasing a version.

**Comment by janpecha** [comment]
Released new version `3.8.0`.
