### ISSUE TITLE
Command 'git add --end-of-options '/media/mehdi/inwork/newsample/readme.txt'' failed (exit-code 128).

### ISSUE THREAD

**Issue by mehdikamari** [czproject/git-php#87]
Command 'git add --end-of-options '...' failed (exit-code 128).

**Comment by mehdikamari** [comment]
$git = new Git();

        // create repo object
        $repo = $git->open($this->location.$repository);

        // create a new file in repo
        $filename = $repo->getRepositoryPath() . '/readme.txt';
        file_put_contents($filename, "Lorem ipsum
        	dolor
        	sit amet
        ");

        // commit
        $repo->addFile($filename);
        $repo->commit('init commit 2');

**Comment by janpecha** [comment]
Hello, try catch exception and print error output:

```php
// commit
try {
	$repo->addFile($filename);
	$repo->commit('init commit 2');

} catch (\CzProject\GitPhp\GitException $e) {
	var_dump($e->getRunnerResult()->toText());
}

```

Your code sample works me without trouble.

**Comment by mehdikamari** [comment]
thanks , i found it , the problem was of the type of repository and it cann't be of type bare .

have a good time .
