### ISSUE TITLE
sample of Clone

### ISSUE THREAD

**Issue by mehdikamari** [czproject/git-php#88]
Hi ,
I need clone repository from http on client PC , have a sample Code with `git-php` . Client send a request for clone and php script response it.

like a 
        'git clone http://web/myscript/repo.git'
        'git pull and push ...'

**Comment by janpecha** [comment]
Hi, try

```php
$git = new Git;
$repo = $git->cloneRepository('http://web/myscript/repo.git');
$repo->pull(........);
$repo->push(........);
```

Or do you mean something else?

**Comment by mehdikamari** [comment]
thanks jan
i need use as a Git server and Client can be Clone/push/pull with Git Client applications indirect and do it just with connective script (git.php)

Of course, I don't know if this possibility exists in `git-php` or not

**Comment by janpecha** [comment]
I think it's not possible.

**Comment by mehdikamari** [comment]
thank you jan , have a good time
