### ISSUE TITLE
[Question] set github credentials

### ISSUE THREAD

**Issue by rogervila** [czproject/git-php#9]
Hello, I want to upload a project into github.

How can I set my github credentials?

Thank you.

**Comment by janpecha** [comment]
Hello, what do you mean? `git remote add`? You can create your own repository class and write custom method, for example:

``` php
class OwnGitRepository extends \Cz\Git\GitRepository
{
	public function addRemote($remote, $url)
	{
		$this->begin()
			->run('git remote add', $remote, $url)
			->end();
	}
}
```

**Comment by rogervila** [comment]
Thank you @janpecha
