### ISSUE TITLE
Github connection tester does not work through http

### ISSUE THREAD

**Issue by 7system7** [czproject/git-php#92]
Hello,

I have a private repository in Github: 7system7/test. I would test my connection w/ this code:

```php
use CzProject\GitPhp\Git;

$git = new Git();
$git->isRemoteUrlReadable('https://<username>:<token>@github.com/7system7/test.git'); // false
```

**It always returns false, however the token has permission for everything.** What have I wrong? 
If I test it the same way in Gitlab or Gitea, it works.

**Comment by 7system7** [comment]
To answer my question: The problem was that, the repository is uninitialized, so it was an **empty repo**.

So, in my opinion, the `isRemoteUrlReadable` method has a bug because the empty repo does not mean, it is unreadable.

**Comment by janpecha** [comment]
Hello, thanks for report :) Please try current `@dev` version, I just committed fix for it.
