### ISSUE TITLE
Looks like addFile cannot handle umlauts

### ISSUE THREAD

**Issue by embeh** [czproject/git-php#97]
The method "addFile" seems to remove any URL-encoded umlauts (e.g. äöü) in the filename...?

Here is a snippet of the code that works just fine with any filename that has no umlaut in it:

```
# the variable $gitfilename contains the string "/tmp/Test,Test G\xc3\xbcnther__test.txt" wich is the encoded form of "/tmp/Test,Test Günther__test.txt"

$val = file_put_contents($gitfilename, $txt, FILE_APPEND);
echo('Successfully written ' . $val . ' bytes to file ' . $gitfilename);
# Output: Successfully written 534 bytes to file /tmp/Test,Test G\xc3\xbcnther__test.txt

# Note that the file is now correctly listed in the file system:
# ls -al
# -rw-rw----  1 user group  534 Jan 29 09:09 'Test,Test Günther__test.txt'

$repo->addFile($gitfilename); 
# git exception: Command 'git add --end-of-options '/tmp/Test,Test Gnther__test.txt'' failed (exit-code 128)
```

**Comment by janpecha** [comment]
Hi, what is your OS? I tried it on Ubuntu 22.04 and it works without error. Maybe some `setlocale()`-specific issue (see https://github.com/PHP-FFMpeg/PHP-FFMpeg/issues/226)?

**Comment by embeh** [comment]
Thanks for looking into this.

I am running this on Ubuntu 20.04 - and YES, setting the locale early on in the code using `setlocale(LC_CTYPE, "en_US.UTF-8")` fixed the problem!

Thanks very much! 👍
